version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    target-branch: "main"
    commit-message:
      prefix: "dependabot"
      include: "scope"
